const products=[
 {id:1,name:'The Everyday',category:'sneakers',price:89,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',tag:'Bestseller'},
 {id:2,name:'Cloud Runner',category:'sneakers',price:110,image:'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=700&q=80',tag:'New'},
 {id:3,name:'The Penny',category:'loafers',price:125,image:'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=700&q=80'},
 {id:4,name:'Easy Slide',category:'sandals',price:65,image:'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=700&q=80'},
 {id:5,name:'Trail Low',category:'boots',price:145,image:'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=700&q=80'},
 {id:6,name:'Canvas Classic',category:'sneakers',price:78,image:'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=700&q=80'},
 {id:7,name:'Mule No. 2',category:'loafers',price:99,image:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=700&q=80'},
 {id:8,name:'Day Hiker',category:'boots',price:135,image:'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=700&q=80'}
];
let bag=JSON.parse(localStorage.getItem('solemate-bag')||'[]');
const grid=document.getElementById('productGrid');
function money(n){return `$${n.toFixed(2)}`}
function renderProducts(filter='all'){grid.innerHTML=products.filter(p=>filter==='all'||p.category===filter).map(p=>`<article class="product-card"><div class="product-image">${p.tag?`<span class="tag">${p.tag}</span>`:''}<img src="${p.image}" alt="${p.name} shoe" loading="lazy"><button class="quick-add" onclick="addToBag(${p.id})">+ Add to bag</button></div><div class="product-info"><div><strong>${p.name}</strong><p>${p.category[0].toUpperCase()+p.category.slice(1)}</p></div><strong>${money(p.price)}</strong></div></article>`).join('')}
function renderBag(){let count=bag.reduce((a,x)=>a+x.qty,0);document.getElementById('cartCount').textContent=count;document.getElementById('drawerCount').textContent=`(${count})`;document.getElementById('cartItems').innerHTML=bag.length?bag.map(x=>`<div class="cart-line"><img src="${x.image}" alt=""><div><h4>${x.name}</h4><p>${money(x.price)} × ${x.qty}</p></div><button class="remove" onclick="removeFromBag(${x.id})">×</button></div>`).join(''):'<div class="empty-cart">Your bag is waiting for something good.</div>';document.getElementById('subtotal').textContent=money(bag.reduce((a,x)=>a+x.price*x.qty,0));localStorage.setItem('solemate-bag',JSON.stringify(bag))}
function addToBag(id){let p=products.find(x=>x.id===id), old=bag.find(x=>x.id===id);old?old.qty++:bag.push({...p,qty:1});renderBag();document.getElementById('toast').classList.add('show');setTimeout(()=>document.getElementById('toast').classList.remove('show'),1800)}
function removeFromBag(id){bag=bag.filter(x=>x.id!==id);renderBag()}
function openCart(){document.getElementById('cartDrawer').classList.add('open');document.getElementById('overlay').classList.add('show')}
function closeCart(){document.getElementById('cartDrawer').classList.remove('open');document.getElementById('overlay').classList.remove('show')}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');renderProducts(b.dataset.filter)}));document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('overlay').onclick=closeCart;document.getElementById('menuBtn').onclick=()=>document.getElementById('mobileNav').classList.toggle('show');document.getElementById('checkoutBtn').onclick=()=>alert('Thank you! Checkout is ready to connect to your payment provider.');document.getElementById('subscribeBtn').onclick=()=>{let e=document.getElementById('email');if(e.value)alert('Thanks for subscribing! Your discount is on its way.');else e.focus()};document.getElementById('searchBtn').onclick=()=>document.getElementById('shop').scrollIntoView();renderProducts();renderBag();
